import { FormEvent, useEffect, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, PlusCircle } from 'lucide-react';
import { api } from '../lib/api';
import { categoryLabel, dateInput, money } from '../lib/format';
import { CashEntry } from '../types';
import { Badge, Empty, Loading, Modal, PageHeader } from '../components/ui';
import { useToast } from '../components/toast';

type CashData = { entries: CashEntry[]; totals: { input: number; output: number; balance: number } };
export function CashPage() {
  const { success, error } = useToast(); const [data, setData] = useState<CashData>(); const [range, setRange] = useState({ start: '', end: '' }); const [formOpen, setFormOpen] = useState(false); const [form, setForm] = useState({ entryType: 'OUT', category: 'EXPENSE', description: '', amount: '', occurredOn: dateInput() });
  const load = () => { const params = new URLSearchParams(Object.entries(range).filter(([, value]) => value)); api<CashData>(`/cash?${params}`).then(setData).catch((err) => error(err.message)); };
  useEffect(load, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); try { await api('/cash', { method: 'POST', body: { ...form, amount: Number(form.amount) } }); success('Lançamento registrado no caixa.'); setFormOpen(false); setForm({ entryType: 'OUT', category: 'EXPENSE', description: '', amount: '', occurredOn: dateInput() }); load(); } catch (err) { error(err instanceof Error ? err.message : 'Não foi possível lançar no caixa.'); } };
  if (!data) return <Loading />;
  return <div><PageHeader title="Caixa" description="Entradas de vendas e lançamentos manuais em um só lugar." action={<button className="button primary" onClick={() => setFormOpen(true)}><PlusCircle size={18} /> Novo lançamento</button>} />
    <div className="cash-grid"><article className="cash-card in"><ArrowUpRight size={23} /><div><small>Entradas</small><strong>{money(data.totals.input)}</strong></div></article><article className="cash-card out"><ArrowDownRight size={23} /><div><small>Saídas</small><strong>{money(data.totals.output)}</strong></div></article><article className="cash-card balance"><div><small>Saldo do período</small><strong>{money(data.totals.balance)}</strong></div></article></div>
    <form className="filters compact" onSubmit={(event) => { event.preventDefault(); load(); }}><label>De<input type="date" value={range.start} onChange={(event) => setRange((current) => ({ ...current, start: event.target.value }))} /></label><label>Até<input type="date" value={range.end} onChange={(event) => setRange((current) => ({ ...current, end: event.target.value }))} /></label><button className="button secondary">Aplicar período</button></form>
    <div className="table-card"><table><thead><tr><th>Data</th><th>Descrição</th><th>Categoria</th><th>Tipo</th><th className="right">Valor</th></tr></thead><tbody>{data.entries.map((entry) => <tr key={entry.id}><td>{new Date(`${entry.occurredOn}T12:00:00`).toLocaleDateString('pt-BR')}</td><td><strong>{entry.description}</strong></td><td>{categoryLabel[entry.category]}</td><td><Badge tone={entry.entryType === 'IN' ? 'success' : 'danger'}>{entry.entryType === 'IN' ? 'Entrada' : 'Saída'}</Badge></td><td className={`right ${entry.entryType === 'IN' ? 'positive' : 'negative'}`}><strong>{entry.entryType === 'IN' ? '+' : '−'} {money(entry.amount)}</strong></td></tr>)}</tbody></table>{!data.entries.length && <Empty>Nenhum lançamento nesse período.</Empty>}</div>
    {formOpen && <Modal title="Novo lançamento no caixa" onClose={() => setFormOpen(false)}><form className="form-grid" onSubmit={submit}><label>Tipo<select value={form.entryType} onChange={(event) => setForm((current) => ({ ...current, entryType: event.target.value }))}><option value="OUT">Saída</option><option value="IN">Entrada</option></select></label><label>Categoria<select value={form.category} onChange={(event) => setForm((current) => ({ ...current, category: event.target.value }))}><option value="EXPENSE">Despesa</option><option value="PURCHASE">Compra</option><option value="OTHER">Outro</option></select></label><label className="full">Descrição *<input required placeholder="Ex.: aluguel, compra de mercadorias" value={form.description} onChange={(event) => setForm((current) => ({ ...current, description: event.target.value }))} /></label><label>Valor *<input required type="number" min="0.01" step="0.01" value={form.amount} onChange={(event) => setForm((current) => ({ ...current, amount: event.target.value }))} /></label><label>Data *<input required type="date" value={form.occurredOn} onChange={(event) => setForm((current) => ({ ...current, occurredOn: event.target.value }))} /></label><div className="form-actions"><button type="button" className="button secondary" onClick={() => setFormOpen(false)}>Cancelar</button><button className="button primary">Registrar lançamento</button></div></form></Modal>}
  </div>;
}
