import { FormEvent, useEffect, useState } from 'react';
import { FileText, Search, Trash2 } from 'lucide-react';
import { api } from '../lib/api';
import { money, paymentLabel, shortDate } from '../lib/format';
import { Sale } from '../types';
import { Badge, Empty, Loading, Modal, PageHeader } from '../components/ui';
import { useToast } from '../components/toast';

export function HistoryPage() {
  const { success, error } = useToast(); const [sales, setSales] = useState<Sale[]>(); const [filters, setFilters] = useState({ plate: '', term: '', startDate: '', endDate: '' }); const [detail, setDetail] = useState<Sale | null>(null); const [deleting, setDeleting] = useState<Sale | null>(null); const [notes, setNotes] = useState(''); const [saving, setSaving] = useState(false);
  const load = () => { const params = new URLSearchParams(Object.entries(filters).filter(([, value]) => value)); api<Sale[]>(`/sales?${params}`).then(setSales).catch((err) => error(err.message)); };
  useEffect(load, []);
  const search = (event: FormEvent) => { event.preventDefault(); load(); };
  const open = async (id: number) => { try { const sale = await api<Sale>(`/sales/${id}`); setDetail(sale); setNotes(sale.notes || ''); } catch (err) { error(err instanceof Error ? err.message : 'Não foi possível abrir a venda.'); } };
  const saveNotes = async () => { if (!detail) return; setSaving(true); try { const sale = await api<Sale>(`/sales/${detail.id}/notes`, { method: 'PATCH', body: { notes: notes || null } }); setDetail(sale); success('Observações atualizadas.'); load(); } catch (err) { error(err instanceof Error ? err.message : 'Não foi possível salvar.'); } finally { setSaving(false); } };
  const deleteSale = async () => { if (!deleting) return; setSaving(true); try { await api(`/sales/${deleting.id}`, { method: 'DELETE' }); success(`Venda ${deleting.saleNumber} excluída e estoque estornado.`); setDeleting(null); load(); } catch (err) { error(err instanceof Error ? err.message : 'Não foi possível excluir a venda.'); } finally { setSaving(false); } };
  if (!sales) return <Loading />;
  return <div><PageHeader title="Histórico de vendas" description="Todas as vendas ficam guardadas permanentemente para consulta." />
    <form className="filters history-filters" onSubmit={search}><label className="search-field"><span>Pesquisar</span><div className="search"><Search size={18} /><input placeholder="Produto, serviço ou veículo" value={filters.term} onChange={(event) => setFilters((current) => ({ ...current, term: event.target.value }))} /></div></label><label><span>Placa</span><input placeholder="ABC1D23" value={filters.plate} onChange={(event) => setFilters((current) => ({ ...current, plate: event.target.value.toUpperCase() }))} /></label><label><span>De</span><input type="date" value={filters.startDate} onChange={(event) => setFilters((current) => ({ ...current, startDate: event.target.value }))} /></label><label><span>Até</span><input type="date" value={filters.endDate} onChange={(event) => setFilters((current) => ({ ...current, endDate: event.target.value }))} /></label><button className="button secondary filter-action">Filtrar</button></form>
    <div className="table-card"><table><thead><tr><th>Venda</th><th>Data e hora</th><th>Veículo</th><th>Itens</th><th>Pagamento</th><th>Total</th><th>Lucro</th><th /></tr></thead><tbody>{sales.map((sale) => <tr key={sale.id}><td><strong>{sale.saleNumber}</strong></td><td>{shortDate(sale.soldAt)}</td><td><strong>{sale.vehiclePlate || '—'}</strong><small>{sale.vehicleModel || 'Sem modelo'}</small></td><td>{sale.items.slice(0, 2).map((item) => item.description).join(', ')}{sale.items.length > 2 ? '…' : ''}</td><td><Badge tone="info">{paymentLabel[sale.paymentMethod]}</Badge></td><td><strong>{money(sale.total)}</strong></td><td className="positive">{money(sale.profit)}</td><td><button className="button small" type="button" onClick={() => open(sale.id)}><FileText size={15} /> Ver</button></td></tr>)}</tbody></table>{!sales.length && <Empty>Nenhuma venda atende aos filtros informados.</Empty>}</div>
    {detail && <Modal title={`Venda ${detail.saleNumber}`} onClose={() => setDetail(null)} width="wide"><div className="sale-detail-top"><div><span>Data e hora</span><strong>{shortDate(detail.soldAt)}</strong></div><div><span>Veículo</span><strong>{detail.vehiclePlate || 'Sem placa'} {detail.vehicleModel ? `— ${detail.vehicleModel}` : ''}</strong></div><div><span>Pagamento</span><strong>{paymentLabel[detail.paymentMethod]}</strong></div><div><span>Lucro</span><strong className="positive">{money(detail.profit)}</strong></div></div><div className="table-card in-modal"><table><thead><tr><th>Item</th><th>Tipo</th><th>Qtd.</th><th>Unitário</th><th>Total</th></tr></thead><tbody>{detail.items.map((item) => <tr key={item.id}><td>{item.description}</td><td>{item.itemType === 'LABOR' ? 'Mão de obra' : item.itemType === 'SERVICE' ? 'Serviço' : 'Produto'}</td><td>{item.quantity}</td><td>{money(item.unitPrice)}</td><td><strong>{money(item.total)}</strong></td></tr>)}</tbody></table></div><div className="detail-totals"><span>Subtotal <b>{money(detail.subtotal)}</b></span><span>Desconto <b>− {money(detail.discount)}</b></span><strong>Total final <b>{money(detail.total)}</b></strong></div><label className="full">Observações (podem ser editadas)<textarea rows={3} value={notes} onChange={(event) => setNotes(event.target.value)} /></label><div className="form-actions detail-actions"><button className="button danger-fill" onClick={() => { setDeleting(detail); setDetail(null); }}><Trash2 size={16} /> Excluir venda</button><span /><button className="button secondary" onClick={() => setDetail(null)}>Fechar</button><button disabled={saving} className="button primary" onClick={saveNotes}>{saving ? 'Salvando…' : 'Salvar observações'}</button></div></Modal>}
    {deleting && <Modal title="Excluir venda e estornar estoque" onClose={() => setDeleting(null)}><p>Deseja excluir permanentemente a venda <strong>{deleting.saleNumber}</strong>?</p><div className="restore-note delete-note"><Trash2 size={17} /> Os produtos desta venda voltarão automaticamente ao estoque e a entrada correspondente será removida do caixa.</div><p className="muted">Essa ação não pode ser desfeita.</p><div className="form-actions"><button className="button secondary" onClick={() => setDeleting(null)}>Cancelar</button><button disabled={saving} className="button danger-fill" onClick={deleteSale}>{saving ? 'Excluindo…' : 'Excluir e estornar'}</button></div></Modal>}
  </div>;
}
