import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Edit3, Eye, EyeOff, PackagePlus, Search, Trash2 } from 'lucide-react';
import { api } from '../lib/api';
import { money, productName, stockLocationLabel } from '../lib/format';
import { Product, ProductType, Settings } from '../types';
import { Badge, Empty, Loading, Modal, PageHeader } from '../components/ui';
import { useToast } from '../components/toast';

type ProductForm = Record<string, string | number | boolean | null>;
const labels: Record<ProductType, { plural: string; singular: string }> = { TIRE: { plural: 'Pneus', singular: 'pneu' }, WHEEL: { plural: 'Rodas', singular: 'roda' }, VALVE: { plural: 'Bicos', singular: 'bico' } };
const blank = (type: ProductType, minimum = 2): ProductForm => ({ type, brand: '', model: '', name: '', tireWidth: '', tireHeight: '', rim: '', tireCondition: 'NOVO', boltPattern: '', wheelWidth: '', valveType: '', stockLocation: 'STOCK', purchasePrice: 0, salePrice: 0, quantity: 0, minimumQuantity: minimum });
const formFrom = (product: Product): ProductForm => ({ ...blank(product.type, product.minimumQuantity), ...product, brand: product.brand || '', model: product.model || '', name: product.name || '', tireWidth: product.tireWidth || '', tireHeight: product.tireHeight || '', rim: product.rim || '', tireCondition: product.tireCondition || 'NOVO', boltPattern: product.boltPattern || '', wheelWidth: product.wheelWidth || '', valveType: product.valveType || '', stockLocation: product.stockLocation || 'STOCK' });

export function ProductsPage({ type }: { type: ProductType }) {
  const { success, error } = useToast(); const [products, setProducts] = useState<Product[]>(); const [search, setSearch] = useState(''); const [onlyLow, setOnlyLow] = useState(false); const [form, setForm] = useState<ProductForm | null>(null); const [editing, setEditing] = useState<Product | null>(null); const [deleting, setDeleting] = useState<Product | null>(null); const [minimum, setMinimum] = useState(2); const [hideCosts, setHideCosts] = useState(false); const [saving, setSaving] = useState(false);
  const reload = () => api<Product[]>(`/products?type=${type}&search=${encodeURIComponent(search)}&lowStock=${onlyLow}`).then(setProducts).catch((err) => error(err.message));
  useEffect(() => { void reload(); }, [type, search, onlyLow]);
  useEffect(() => { api<Settings>('/settings').then((settings) => { setMinimum(settings.defaultMinimumStock); setHideCosts(settings.hideCostInInventory); }).catch(() => {}); }, []);
  const toggleCosts = async () => { const next = !hideCosts; setHideCosts(next); try { const settings = await api<Settings>('/settings', { method: 'PUT', body: { hideCostInInventory: next } }); setHideCosts(settings.hideCostInInventory); success(next ? 'Preços de custo ocultados.' : 'Preços de custo visíveis.'); } catch (err) { setHideCosts(!next); error(err instanceof Error ? err.message : 'Não foi possível alterar a privacidade dos custos.'); } };
  const title = labels[type].plural;
  const searchPlaceholder = type === 'TIRE' ? 'Pesquisar marca, modelo ou medida (ex.: 205/55 R16)…' : `Pesquisar ${title.toLowerCase()}…`;
  const fields = useMemo(() => type === 'TIRE'
    ? [['Marca', 'brand', true], ['Modelo', 'model', true], ['Largura', 'tireWidth', true], ['Altura', 'tireHeight', true], ['Aro', 'rim', true]]
    : type === 'WHEEL' ? [['Marca', 'brand', false], ['Modelo', 'model', false], ['Furação', 'boltPattern', true], ['Aro', 'rim', true], ['Tala', 'wheelWidth', true]]
    : [['Nome', 'name', true], ['Tipo', 'valveType', false]], [type]);
  const update = (key: string, value: string) => setForm((current) => current ? { ...current, [key]: value } : current);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!form) return; setSaving(true); try { const payload = { ...form, purchasePrice: Number(form.purchasePrice), salePrice: Number(form.salePrice), quantity: Number(form.quantity), minimumQuantity: Number(form.minimumQuantity) }; if (editing) await api(`/products/${editing.id}`, { method: 'PUT', body: payload }); else await api('/products', { method: 'POST', body: payload }); success(editing ? `${labels[type].singular} atualizado.` : `${labels[type].singular} cadastrado e incluído no estoque.`); setForm(null); setEditing(null); reload(); } catch (err) { error(err instanceof Error ? err.message : 'Não foi possível salvar.'); } finally { setSaving(false); } };
  const remove = async () => { if (!deleting) return; try { await api(`/products/${deleting.id}`, { method: 'DELETE' }); success('Produto removido do cadastro. O histórico de vendas foi preservado.'); setDeleting(null); reload(); } catch (err) { error(err instanceof Error ? err.message : 'Não foi possível excluir.'); } };
  if (!products) return <Loading />;
  return <div><PageHeader title={title} description={`Cadastre e mantenha o estoque de ${title.toLowerCase()} atualizado.`} action={<button className="button primary" onClick={() => { setEditing(null); setForm(blank(type, minimum)); }}><PackagePlus size={18} /> Cadastrar {labels[type].singular}</button>} />
    <div className="toolbar"><label className="search"><Search size={18} /><input autoFocus placeholder={searchPlaceholder} value={search} onChange={(event) => setSearch(event.target.value)} /></label><label className="check-label"><input type="checkbox" checked={onlyLow} onChange={(event) => setOnlyLow(event.target.checked)} /> Somente estoque baixo</label><button type="button" className="button secondary" onClick={toggleCosts}>{hideCosts ? <Eye size={16} /> : <EyeOff size={16} />}{hideCosts ? 'Mostrar custos' : 'Ocultar custos'}</button><span className="records-count">{products.length} item(ns)</span></div>
    <div className="table-card"><table><thead><tr><th>Produto</th>{type === 'TIRE' && <th>Localização</th>}{!hideCosts && <th>Compra</th>}<th>Venda</th><th>Estoque</th><th className="right">Ações</th></tr></thead><tbody>{products.map((product) => <tr key={product.id}><td><strong>{productName(product)}</strong><small>{type === 'TIRE' ? product.tireCondition : type === 'VALVE' ? product.valveType : product.boltPattern}</small></td>{type === 'TIRE' && <td><Badge tone="info">{stockLocationLabel[product.stockLocation]}</Badge></td>}{!hideCosts && <td>{money(product.purchasePrice)}</td>}<td><strong>{money(product.salePrice)}</strong></td><td>{product.lowStock ? <Badge tone="warning">{product.quantity} / mín. {product.minimumQuantity}</Badge> : <Badge tone="success">{product.quantity} un.</Badge>}</td><td className="right"><button className="table-button" title="Editar" onClick={() => { setEditing(product); setForm(formFrom(product)); }}><Edit3 size={17} /></button><button className="table-button danger" title="Excluir" onClick={() => setDeleting(product)}><Trash2 size={17} /></button></td></tr>)}</tbody></table>{!products.length && <Empty>Cadastre o primeiro {labels[type].singular} para começar.</Empty>}</div>
    {form && <Modal title={`${editing ? 'Editar' : 'Cadastrar'} ${labels[type].singular}`} onClose={() => { setForm(null); setEditing(null); }}><form onSubmit={submit} className="form-grid">{fields.map(([label, key, required]) => <label key={key as string}>{label}{required ? ' *' : ''}<input required={Boolean(required)} value={String(form[key as string] ?? '')} onChange={(event) => update(key as string, event.target.value)} /></label>)}
      {type === 'TIRE' && <><label>Condição *<select value={String(form.tireCondition)} onChange={(event) => update('tireCondition', event.target.value)}><option value="NOVO">Novo</option><option value="REMODELADO">Remoldado</option></select></label><label>Localização *<select value={String(form.stockLocation)} onChange={(event) => update('stockLocation', event.target.value)}><option value="PAINT_STOCK">Estoque pintura</option><option value="STOCK">Estoque</option><option value="STORE">Loja</option></select></label></>}
      <label>Preço de compra *<input required type="number" min="0" step="0.01" value={String(form.purchasePrice)} onChange={(event) => update('purchasePrice', event.target.value)} /></label><label>Preço de venda *<input required type="number" min="0" step="0.01" value={String(form.salePrice)} onChange={(event) => update('salePrice', event.target.value)} /></label>
      {!editing ? <label>Quantidade inicial *<input required type="number" min="0" step="1" value={String(form.quantity)} onChange={(event) => update('quantity', event.target.value)} /></label> : <div className="form-hint">Estoque atual: <b>{editing.quantity} un.</b><br />Para ajustar, use a tela Estoque.</div>}
      <label>Estoque mínimo *<input required type="number" min="0" step="1" value={String(form.minimumQuantity)} onChange={(event) => update('minimumQuantity', event.target.value)} /></label><div className="form-actions"><button type="button" className="button secondary" onClick={() => { setForm(null); setEditing(null); }}>Cancelar</button><button disabled={saving} className="button primary">{saving ? 'Salvando…' : 'Salvar'}</button></div></form></Modal>}
    {deleting && <Modal title="Remover produto" onClose={() => setDeleting(null)}><p>Deseja remover <strong>{productName(deleting)}</strong> do cadastro?</p><p className="muted">Se ele já apareceu em vendas, será apenas arquivado para preservar o histórico.</p><div className="form-actions"><button className="button secondary" onClick={() => setDeleting(null)}>Cancelar</button><button className="button danger-fill" onClick={remove}>Remover</button></div></Modal>}
  </div>;
}
