import { FormEvent, useEffect, useState } from 'react';
import * as XLSX from 'xlsx';
import { Download, FileSpreadsheet, FileText, TrendingUp } from 'lucide-react';
import { api } from '../lib/api';
import { dateInput, money } from '../lib/format';
import { Empty, Loading, PageHeader } from '../components/ui';
import { useToast } from '../components/toast';

type Report = { range: { start: string; end: string }; overview: { revenue: number; profit: number; salesCount: number }; daily: Array<{ date: string; revenue: number; profit: number; salesCount: number }>; products: Array<{ description: string; quantity: number; revenue: number }>; services: Array<{ description: string; quantity: number; revenue: number }> };
const firstOfMonth = () => `${dateInput().slice(0, 8)}01`;

export function ReportsPage() {
  const { success, error } = useToast(); const [report, setReport] = useState<Report>(); const [range, setRange] = useState({ start: firstOfMonth(), end: dateInput() });
  const load = () => api<Report>(`/reports?start=${range.start}&end=${range.end}`).then(setReport).catch((err) => error(err.message));
  useEffect(() => { void load(); }, []);
  const submit = (event: FormEvent) => { event.preventDefault(); load(); };
  const exportExcel = () => { if (!report) return; const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(report.daily.map((item) => ({ Data: item.date, Faturamento: item.revenue, Lucro: item.profit, Vendas: item.salesCount }))), 'Diário'); XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(report.products.map((item) => ({ Produto: item.description, Quantidade: item.quantity, Faturamento: item.revenue }))), 'Produtos'); XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(report.services.map((item) => ({ Serviço: item.description, Quantidade: item.quantity, Faturamento: item.revenue }))), 'Serviços'); XLSX.writeFile(workbook, `relatorio-pneu-pro-${report.range.start}-${report.range.end}.xlsx`); success('Planilha Excel gerada.'); };
  const exportPdf = async () => { if (!report) return; const table = (title: string, headers: string[], rows: string[][]) => `<h2>${title}</h2><table><thead><tr>${headers.map((header) => `<th>${header}</th>`).join('')}</tr></thead><tbody>${rows.map((row) => `<tr>${row.map((value) => `<td>${value}</td>`).join('')}</tr>`).join('')}</tbody></table>`; const html = `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><style>body{font-family:Arial,sans-serif;color:#14201f;padding:30px}h1{color:#0f766e;margin-bottom:2px}p{color:#667}table{width:100%;border-collapse:collapse;margin:16px 0 28px}th{background:#e5f3f0;text-align:left}th,td{padding:8px;border-bottom:1px solid #d9e1df;font-size:12px}.summary{display:flex;gap:28px;margin:25px 0}.summary div{background:#f3f7f6;padding:14px;border-radius:8px;min-width:150px}.summary span{display:block;color:#667;font-size:11px}.summary b{font-size:19px}</style></head><body><h1>Relatório Pneu Pro Gestão</h1><p>Período: ${report.range.start.split('-').reverse().join('/')} a ${report.range.end.split('-').reverse().join('/')}</p><div class="summary"><div><span>Faturamento</span><b>${money(report.overview.revenue)}</b></div><div><span>Lucro</span><b>${money(report.overview.profit)}</b></div><div><span>Vendas</span><b>${report.overview.salesCount}</b></div></div>${table('Faturamento e lucro diário', ['Data','Faturamento','Lucro','Vendas'], report.daily.map((item) => [item.date.split('-').reverse().join('/'),money(item.revenue),money(item.profit),String(item.salesCount)]))}${table('Produtos mais vendidos', ['Produto','Quantidade','Faturamento'], report.products.map((item) => [item.description,String(item.quantity),money(item.revenue)]))}${table('Serviços mais realizados', ['Serviço','Quantidade','Faturamento'], report.services.map((item) => [item.description,String(item.quantity),money(item.revenue)]))}</body></html>`; if (window.desktop) { const result = await window.desktop.saveReportPdf(html); if (!result.canceled) success('PDF salvo com sucesso.'); } else { const tab = window.open('', '_blank'); if (tab) { tab.document.write(html); tab.document.close(); tab.print(); } } };
  if (!report) return <Loading />;
  return <div><PageHeader title="Relatórios" description="Resultados objetivos para acompanhar faturamento, lucro e itens vendidos." action={<div className="header-actions"><button className="button secondary" onClick={exportExcel}><FileSpreadsheet size={18} /> Excel</button><button className="button primary" onClick={exportPdf}><FileText size={18} /> PDF</button></div>} />
    <form className="filters compact" onSubmit={submit}><label>De<input type="date" value={range.start} onChange={(event) => setRange((current) => ({ ...current, start: event.target.value }))} /></label><label>Até<input type="date" value={range.end} onChange={(event) => setRange((current) => ({ ...current, end: event.target.value }))} /></label><button className="button secondary"><Download size={17} /> Atualizar</button></form>
    <div className="report-kpis"><article><TrendingUp size={23} /><div><small>Faturamento</small><strong>{money(report.overview.revenue)}</strong></div></article><article><TrendingUp size={23} /><div><small>Lucro</small><strong className="positive">{money(report.overview.profit)}</strong></div></article><article><div><small>Vendas realizadas</small><strong>{report.overview.salesCount}</strong></div></article></div>
    <section className="reports-grid"><article className="panel"><div className="panel-heading"><div><h2>Faturamento diário</h2><p>Faturamento e lucro por dia.</p></div></div><div className="table-card in-panel"><table><thead><tr><th>Data</th><th>Vendas</th><th>Faturamento</th><th>Lucro</th></tr></thead><tbody>{report.daily.map((item) => <tr key={item.date}><td>{item.date.split('-').reverse().join('/')}</td><td>{item.salesCount}</td><td>{money(item.revenue)}</td><td className="positive">{money(item.profit)}</td></tr>)}</tbody></table>{!report.daily.length && <Empty>Sem vendas no período.</Empty>}</div></article>
      <article className="panel"><div className="panel-heading"><div><h2>Produtos mais vendidos</h2><p>Ordenado pela quantidade vendida.</p></div></div><Ranking rows={report.products} name="Produto" /></article><article className="panel"><div className="panel-heading"><div><h2>Serviços mais realizados</h2><p>Inclui mão de obra livre.</p></div></div><Ranking rows={report.services} name="Serviço" /></article></section>
  </div>;
}

function Ranking({ rows, name }: { rows: Array<{ description: string; quantity: number; revenue: number }>; name: string }) { return rows.length ? <ol className="ranking">{rows.map((item, index) => <li key={`${item.description}-${index}`}><span>{index + 1}</span><div><strong>{item.description}</strong><small>{item.quantity} realizado(s)</small></div><b>{money(item.revenue)}</b></li>)}</ol> : <Empty>Sem {name.toLowerCase()}s no período.</Empty>; }
