import { FormEvent, useEffect, useMemo, useState } from 'react';
import { CirclePlus, Minus, PackagePlus, PackageSearch, Plus, ReceiptText, Search, Trash2, Wrench } from 'lucide-react';
import { api } from '../lib/api';
import { money, productName, stockLocationLabel } from '../lib/format';
import { CatalogService, PaymentMethod, Product } from '../types';
import { Badge, Empty, Loading, PageHeader } from '../components/ui';
import { useToast } from '../components/toast';

type CartItem = { key: string; itemType: 'PRODUCT' | 'SERVICE' | 'LABOR' | 'PART'; productId?: number; serviceCode?: 'ALIGNMENT' | 'BALANCING'; description: string; quantity: number; unitPrice: number; unitCost?: number; available?: number };
const payments: Array<[PaymentMethod, string]> = [['CASH', 'Dinheiro'], ['PIX', 'PIX'], ['CARD', 'Cartão'], ['OTHER', 'Outro']];

export function SalePage() {
  const { success, error } = useToast(); const [products, setProducts] = useState<Product[]>(); const [services, setServices] = useState<CatalogService[]>(); const [query, setQuery] = useState(''); const [items, setItems] = useState<CartItem[]>([]); const [vehiclePlate, setVehiclePlate] = useState(''); const [vehicleModel, setVehicleModel] = useState(''); const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>('PIX'); const [discountType, setDiscountType] = useState<'' | 'FIXED' | 'PERCENT'>(''); const [discountValue, setDiscountValue] = useState(0); const [notes, setNotes] = useState(''); const [labor, setLabor] = useState({ description: '', price: '' }); const [part, setPart] = useState({ description: '', cost: '', price: '' }); const [saving, setSaving] = useState(false);
  const reload = () => { api<Product[]>('/products').then(setProducts).catch((err) => error(err.message)); api<CatalogService[]>('/services').then(setServices).catch((err) => error(err.message)); };
  useEffect(reload, []);
  const filtered = useMemo(() => {
    const terms = query.toUpperCase().match(/[A-ZÀ-Ÿ]+\d+|[A-ZÀ-Ÿ]+|\d+/g) || [];
    return (products || []).filter((product) => product.quantity > 0 && terms.every((term) => productName(product).toUpperCase().includes(term))).slice(0, 9);
  }, [products, query]);
  const subtotal = items.reduce((total, item) => total + item.unitPrice * item.quantity, 0);
  const discount = discountType === 'PERCENT' ? Math.min(subtotal, subtotal * discountValue / 100) : discountType === 'FIXED' ? Math.min(subtotal, discountValue) : 0;
  const total = subtotal - discount;
  const addProduct = (product: Product) => setItems((current) => { const existing = current.find((item) => item.itemType === 'PRODUCT' && item.productId === product.id); if (existing) return current.map((item) => item.key === existing.key ? { ...item, quantity: Math.min(item.quantity + 1, product.quantity) } : item); return [...current, { key: `product-${product.id}`, itemType: 'PRODUCT', productId: product.id, description: productName(product), quantity: 1, unitPrice: product.salePrice, available: product.quantity }]; });
  const addService = (service: CatalogService) => setItems((current) => [...current, { key: `${service.code}-${Date.now()}`, itemType: 'SERVICE', serviceCode: service.code, description: service.name, quantity: 1, unitPrice: service.price }]);
  const addLabor = () => { const price = Number(labor.price); if (!labor.description.trim() || !Number.isFinite(price) || price < 0) { error('Informe a descrição e um valor válido para a mão de obra.'); return; } setItems((current) => [...current, { key: `labor-${Date.now()}`, itemType: 'LABOR', description: labor.description.trim(), quantity: 1, unitPrice: price }]); setLabor({ description: '', price: '' }); };
  const addPart = () => { const cost = Number(part.cost); const price = Number(part.price); if (!part.description.trim() || part.cost === '' || part.price === '' || !Number.isFinite(cost) || !Number.isFinite(price) || cost < 0 || price < 0) { error('Informe o nome, o custo e o preço de venda da peça.'); return; } setItems((current) => [...current, { key: `part-${Date.now()}`, itemType: 'PART', description: part.description.trim(), quantity: 1, unitPrice: price, unitCost: cost }]); setPart({ description: '', cost: '', price: '' }); };
  const updateItem = (key: string, patch: Partial<CartItem>) => setItems((current) => current.map((item) => item.key === key ? { ...item, ...patch } : item));
  const removeItem = (key: string) => setItems((current) => current.filter((item) => item.key !== key));
  const finish = async (event: FormEvent) => { event.preventDefault(); if (!items.length) { error('Adicione pelo menos um produto, serviço ou peça à venda.'); return; } setSaving(true); try { const sale = await api<{ saleNumber: string }>('/sales', { method: 'POST', body: { vehiclePlate: vehiclePlate || null, vehicleModel: vehicleModel || null, paymentMethod, notes: notes || null, discountType: discountType || null, discountValue, items: items.map(({ itemType, productId, serviceCode, description, quantity, unitPrice, unitCost }) => ({ itemType, productId, serviceCode, description, quantity, unitPrice, unitCost })) } }); success(`Venda ${sale.saleNumber} finalizada com sucesso.`); setItems([]); setVehiclePlate(''); setVehicleModel(''); setPaymentMethod('PIX'); setDiscountType(''); setDiscountValue(0); setNotes(''); reload(); } catch (err) { error(err instanceof Error ? err.message : 'Não foi possível finalizar a venda.'); } finally { setSaving(false); } };
  if (!products || !services) return <Loading />;
  return <div className="sale-page"><PageHeader title="Nova venda" description="Adicione itens, confira o total e finalize em poucos passos." />
    <form onSubmit={finish} className="sale-layout"><section className="sale-workspace"><article className="panel customer-panel"><h2>Veículo</h2><div className="inline-fields"><label>Placa<input placeholder="ABC1D23" value={vehiclePlate} onChange={(event) => setVehiclePlate(event.target.value.toUpperCase())} /></label><label>Modelo do veículo<input placeholder="Ex.: Onix 1.0" value={vehicleModel} onChange={(event) => setVehicleModel(event.target.value)} /></label></div></article>
      <article className="panel"><div className="panel-heading"><div><h2>Adicionar produtos</h2><p>Pesquise pneus, rodas e bicos disponíveis.</p></div></div><label className="search product-search"><Search size={18} /><input placeholder="Digite marca, modelo ou medida…" value={query} onChange={(event) => setQuery(event.target.value)} /></label><div className="product-picker">{filtered.map((product) => <button type="button" key={product.id} onClick={() => addProduct(product)}><div><strong>{productName(product)}</strong><small>{product.type === 'TIRE' ? `${stockLocationLabel[product.stockLocation]} • ` : ''}{product.quantity} un. disponível(is)</small></div><span>{money(product.salePrice)} <Plus size={15} /></span></button>)}{query && !filtered.length && <Empty>Nenhum produto disponível para essa busca.</Empty>}</div></article>
      <article className="panel"><div className="panel-heading"><div><h2>Serviços</h2><p>Use os valores tabelados ou registre mão de obra livre.</p></div></div><div className="quick-services">{services.map((service) => <button type="button" key={service.code} onClick={() => addService(service)}><CirclePlus size={18} /><span>{service.name}</span><b>{money(service.price)}</b></button>)}</div><div className="labor-entry"><Wrench size={19} /><input placeholder="Mão de obra — ex.: troca de pastilhas" value={labor.description} onChange={(event) => setLabor((current) => ({ ...current, description: event.target.value }))} /><input className="labor-price" type="number" min="0" step="0.01" placeholder="Valor" value={labor.price} onChange={(event) => setLabor((current) => ({ ...current, price: event.target.value }))} /><button type="button" className="button secondary" onClick={addLabor}>Adicionar</button></div></article>
      <article className="panel"><div className="panel-heading"><div><h2>Peças avulsas</h2><p>Registre uma peça usada nesta venda sem criar ou alterar o estoque.</p></div></div><div className="part-entry"><PackagePlus size={19} /><input placeholder="Nome da peça — ex.: pastilha de freio" value={part.description} onChange={(event) => setPart((current) => ({ ...current, description: event.target.value }))} /><input type="number" min="0" step="0.01" placeholder="Custo" value={part.cost} onChange={(event) => setPart((current) => ({ ...current, cost: event.target.value }))} /><input type="number" min="0" step="0.01" placeholder="Preço de venda" value={part.price} onChange={(event) => setPart((current) => ({ ...current, price: event.target.value }))} /><button type="button" className="button secondary" onClick={addPart}>Adicionar</button></div></article>
      <article className="panel notes-panel"><label>Observações<input placeholder="Detalhes importantes da venda (opcional)" value={notes} onChange={(event) => setNotes(event.target.value)} /></label></article></section>
      <aside className="sale-summary"><div className="summary-head"><ReceiptText size={21} /><h2>Resumo da venda</h2></div>{items.length ? <div className="cart-items">{items.map((item) => <div className="cart-row" key={item.key}><div className="cart-row-title"><strong>{item.description}</strong><small>{item.itemType === 'PART' ? 'Peça avulsa' : item.itemType === 'LABOR' ? 'Mão de obra' : item.itemType === 'SERVICE' ? 'Serviço' : 'Produto'}</small></div><button type="button" className="remove-line" onClick={() => removeItem(item.key)} title="Remover item"><Trash2 size={16} /></button><div className="line-controls"><div className="quantity-control"><button type="button" onClick={() => updateItem(item.key, { quantity: Math.max(1, item.quantity - 1) })}><Minus size={14} /></button><input type="number" min="1" max={item.available} value={item.quantity} onChange={(event) => updateItem(item.key, { quantity: Math.max(1, Math.min(item.available || Infinity, Number(event.target.value))) })} /><button type="button" disabled={item.available !== undefined && item.quantity >= item.available} onClick={() => updateItem(item.key, { quantity: item.quantity + 1 })}><Plus size={14} /></button></div><label className="line-price">R$<input type="number" min="0" step="0.01" value={item.unitPrice} onChange={(event) => updateItem(item.key, { unitPrice: Number(event.target.value) })} /></label><b>{money(item.unitPrice * item.quantity)}</b></div></div>)}</div> : <Empty>Adicione produtos, serviços ou peças para começar.</Empty>}
        <div className="summary-calculation"><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div className="discount-line"><select aria-label="Tipo de desconto" value={discountType} onChange={(event) => { setDiscountType(event.target.value as '' | 'FIXED' | 'PERCENT'); setDiscountValue(0); }}><option value="">Sem desconto</option><option value="FIXED">Desconto em R$</option><option value="PERCENT">Desconto em %</option></select>{discountType && <input aria-label="Valor do desconto" type="number" min="0" max={discountType === 'PERCENT' ? 100 : undefined} step="0.01" value={discountValue} onChange={(event) => setDiscountValue(Number(event.target.value))} />}</div>{discount > 0 && <div><span>Desconto aplicado</span><b className="negative">− {money(discount)}</b></div>}<div className="total-line"><span>Total</span><strong>{money(total)}</strong></div></div>
        <div className="payment-options"><span>Forma de pagamento</span><div>{payments.map(([value, label]) => <button type="button" className={paymentMethod === value ? 'selected' : ''} onClick={() => setPaymentMethod(value)} key={value}>{label}</button>)}</div></div><button disabled={!items.length || saving} className="button primary finalize"><PackageSearch size={19} /> {saving ? 'Finalizando…' : `Finalizar venda • ${money(total)}`}</button></aside>
    </form></div>;
}
