import { ChangeEvent, FormEvent, useEffect, useState } from 'react';
import { DatabaseBackup, Download, RotateCcw, Save, ShieldCheck, Upload } from 'lucide-react';
import { api, downloadBackup } from '../lib/api';
import { Settings } from '../types';
import { Loading, PageHeader } from '../components/ui';
import { useToast } from '../components/toast';

export function SettingsPage() {
  const { success, error } = useToast(); const [settings, setSettings] = useState<Settings>(); const [saving, setSaving] = useState(false); const [importing, setImporting] = useState(false);
  useEffect(() => { api<Settings>('/settings').then(setSettings).catch((err) => error(err.message)); }, []);
  const save = async (event: FormEvent) => { event.preventDefault(); if (!settings) return; setSaving(true); try { const saved = await api<Settings>('/settings', { method: 'PUT', body: settings }); setSettings(saved); success('Configurações salvas.'); } catch (err) { error(err instanceof Error ? err.message : 'Não foi possível salvar.'); } finally { setSaving(false); } };
  const backup = async () => { try { await downloadBackup(); success('Backup exportado. Guarde o arquivo em local seguro.'); } catch (err) { error(err instanceof Error ? err.message : 'Não foi possível criar o backup.'); } };
  const restore = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (!window.confirm('Restaurar este backup substituirá os dados atuais. Um backup de segurança será criado automaticamente. Deseja continuar?')) { event.target.value = ''; return; } setImporting(true); try { const text = await file.arrayBuffer(); const data = btoa(Array.from(new Uint8Array(text)).map((byte) => String.fromCharCode(byte)).join('')); await api('/backups/import', { method: 'POST', body: { data } }); success('Backup restaurado. Atualize a tela para carregar os dados recuperados.'); } catch (err) { error(err instanceof Error ? err.message : 'Não foi possível restaurar esse arquivo.'); } finally { setImporting(false); event.target.value = ''; } };
  if (!settings) return <Loading />;
  return <div><PageHeader title="Configurações" description="Preferências do sistema e proteção dos seus dados." />
    <div className="settings-layout"><form className="panel settings-form" onSubmit={save}><div className="panel-heading"><div><h2>Empresa e estoque</h2><p>Essas informações ajudam a padronizar o uso diário.</p></div></div><label>Nome da empresa<input value={settings.companyName} onChange={(event) => setSettings((current) => current ? { ...current, companyName: event.target.value } : current)} /></label><label>Estoque mínimo padrão<input type="number" min="0" step="1" value={settings.defaultMinimumStock} onChange={(event) => setSettings((current) => current ? { ...current, defaultMinimumStock: Number(event.target.value) } : current)} /><small>Aplicado como sugestão ao cadastrar novos produtos.</small></label><label className="switch-row"><input type="checkbox" checked={settings.automaticBackup} onChange={(event) => setSettings((current) => current ? { ...current, automaticBackup: event.target.checked } : current)} /><span><b>Backup automático diário</b><small>Cria uma cópia local antes do uso diário.</small></span></label><label className="switch-row"><input type="checkbox" checked={settings.hideCostInInventory} onChange={(event) => setSettings((current) => current ? { ...current, hideCostInInventory: event.target.checked } : current)} /><span><b>Ocultar preços de custo no estoque</b><small>Esconde a coluna de compra nas listagens de pneus, rodas e bicos.</small></span></label><div className="form-actions"><button disabled={saving} className="button primary"><Save size={18} /> {saving ? 'Salvando…' : 'Salvar configurações'}</button></div></form>
      <section className="panel backup-panel"><div className="panel-heading"><div><h2>Backup e restauração</h2><p>Seus dados ficam somente neste computador. Faça cópias frequentes em pendrive ou nuvem.</p></div><ShieldCheck size={28} /></div><div className="backup-actions"><button className="backup-action" onClick={backup}><Download size={23} /><span><b>Exportar banco de dados</b><small>Salva uma cópia completa em arquivo .db</small></span></button><label className={`backup-action ${importing ? 'disabled' : ''}`}><Upload size={23} /><span><b>{importing ? 'Restaurando…' : 'Importar backup'}</b><small>Substitui os dados pelo arquivo selecionado</small></span><input disabled={importing} type="file" accept=".db,.sqlite,.sqlite3" onChange={restore} /></label></div><div className="restore-note"><RotateCcw size={17} /> Antes de restaurar, o sistema cria uma cópia automática do banco atual para evitar perda de dados.</div></section></div>
  </div>;
}
