import { FormEvent, useEffect, useState } from 'react';
import { ArrowDownToLine, ArrowUpFromLine, History, Search, SlidersHorizontal } from 'lucide-react';
import { api } from '../lib/api';
import { productName } from '../lib/format';
import { Product } from '../types';
import { Badge, Empty, Loading, Modal, PageHeader } from '../components/ui';
import { useToast } from '../components/toast';

type Movement = { id: number; movement_type: string; quantity_change: number; quantity_after: number; reason?: string; created_at: string };

export function StockPage() {
  const { success, error } = useToast(); const [products, setProducts] = useState<Product[]>(); const [search, setSearch] = useState(''); const [selected, setSelected] = useState<Product | null>(null); const [history, setHistory] = useState<Product | null>(null); const [movements, setMovements] = useState<Movement[]>([]); const [movement, setMovement] = useState({ type: 'IN', quantity: 1, reason: '' });
  const reload = () => api<Product[]>(`/products?search=${encodeURIComponent(search)}`).then(setProducts).catch((err) => error(err.message));
  useEffect(() => { void reload(); }, [search]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!selected) return; try { await api(`/products/${selected.id}/stock`, { method: 'POST', body: movement }); success('Estoque atualizado.'); setSelected(null); reload(); } catch (err) { error(err instanceof Error ? err.message : 'Não foi possível atualizar.'); } };
  const openHistory = async (product: Product) => { setHistory(product); try { setMovements(await api<Movement[]>(`/products/${product.id}/movements`)); } catch (err) { error(err instanceof Error ? err.message : 'Não foi possível carregar o histórico.'); } };
  if (!products) return <Loading />;
  return <div><PageHeader title="Estoque" description="Registre entradas, saídas e ajustes. As vendas são baixadas automaticamente." />
    <div className="toolbar"><label className="search"><Search size={18} /><input autoFocus placeholder="Pesquisar qualquer produto…" value={search} onChange={(event) => setSearch(event.target.value)} /></label><span className="records-count">{products.length} item(ns)</span></div>
    <div className="table-card"><table><thead><tr><th>Produto</th><th>Tipo</th><th>Disponível</th><th>Mínimo</th><th className="right">Movimentar</th></tr></thead><tbody>{products.map((product) => <tr key={product.id}><td><strong>{productName(product)}</strong><small>{product.type === 'TIRE' ? 'Pneu' : product.type === 'WHEEL' ? 'Roda' : 'Bico'}</small></td><td>{product.lowStock ? <Badge tone="warning">Atenção</Badge> : <Badge tone="success">Normal</Badge>}</td><td><strong>{product.quantity} un.</strong></td><td>{product.minimumQuantity} un.</td><td className="right"><button className="table-button" title="Histórico de movimentos" onClick={() => openHistory(product)}><History size={17} /></button><button className="button small" onClick={() => { setSelected(product); setMovement({ type: 'IN', quantity: 1, reason: '' }); }}><SlidersHorizontal size={15} /> Ajustar</button></td></tr>)}</tbody></table>{!products.length && <Empty>Não há produtos cadastrados no estoque.</Empty>}</div>
    {selected && <Modal title={`Movimentar: ${productName(selected)}`} onClose={() => setSelected(null)}><form onSubmit={submit} className="form-grid"><label>Operação<select value={movement.type} onChange={(event) => setMovement((current) => ({ ...current, type: event.target.value }))}><option value="IN">Entrada de mercadoria</option><option value="OUT">Saída manual</option><option value="ADJUSTMENT">Definir quantidade exata</option></select></label><label>{movement.type === 'ADJUSTMENT' ? 'Quantidade final' : 'Quantidade'}<input type="number" min="0" step="1" value={movement.quantity} onChange={(event) => setMovement((current) => ({ ...current, quantity: Number(event.target.value) }))} /></label><label className="full">Motivo / observação<input placeholder="Ex.: compra, perda, inventário" value={movement.reason} onChange={(event) => setMovement((current) => ({ ...current, reason: event.target.value }))} /></label><div className="form-actions"><button type="button" className="button secondary" onClick={() => setSelected(null)}>Cancelar</button><button className="button primary">{movement.type === 'IN' ? <ArrowDownToLine size={17} /> : <ArrowUpFromLine size={17} />} Confirmar</button></div></form></Modal>}
    {history && <Modal title={`Histórico: ${productName(history)}`} onClose={() => setHistory(null)} width="wide"><div className="table-card in-modal"><table><thead><tr><th>Data</th><th>Movimento</th><th>Alteração</th><th>Saldo</th><th>Motivo</th></tr></thead><tbody>{movements.map((item) => <tr key={item.id}><td>{new Date(item.created_at).toLocaleString('pt-BR')}</td><td>{item.movement_type}</td><td className={item.quantity_change > 0 ? 'positive' : 'negative'}>{item.quantity_change > 0 ? '+' : ''}{item.quantity_change}</td><td>{item.quantity_after}</td><td>{item.reason || '—'}</td></tr>)}</tbody></table>{!movements.length && <Empty>Sem movimentos registrados.</Empty>}</div></Modal>}
  </div>;
}
